package com.sfb;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.sfb.objects.Drone;
import com.sfb.objects.DroneController;
import com.sfb.objects.PlasmaTorpedo;
import com.sfb.objects.Seeker;
import com.sfb.objects.Ship;
import com.sfb.objects.Unit;
import com.sfb.objects.shuttles.Shuttle;
import com.sfb.properties.Location;
import com.sfb.utilities.MapUtils;
import com.sfb.weapons.ESG;
import com.sfb.weapons.Weapon;

/**
 * Expanding Sphere Generator fields (G23.0). Each impulse, for every active ESG,
 * the ring of hexes at its radius is recomputed around the generating ship's
 * current position (the field moves with the ship, G23.45), and any unit that
 * ENTERS a ring hex this impulse takes damage (G23.51). Ships take it on the
 * facing shield; drones are destroyed; the field's strength depletes and it
 * collapses at 0 or after 32 impulses (G23.32). Plasma torpedoes are immune
 * (G23.81).
 *
 * <p>Slice 1: entry is detected from the ship's and unit's positions this
 * impulse vs. the start of the impulse (shared {@code prevLocations}); damage is
 * split sequentially rather than by the G23.52 priority order.
 */
class EsgResolver {

    private final Game game;
    private final List<Ship> ships;
    private final List<Seeker> seekers;
    private final List<Shuttle> activeShuttles;
    private final Map<Unit, Location> prevLocations;

    EsgResolver(Game game, List<Ship> ships, List<Seeker> seekers,
                List<Shuttle> activeShuttles, Map<Unit, Location> prevLocations) {
        this.game           = game;
        this.ships          = ships;
        this.seekers        = seekers;
        this.activeShuttles = activeShuttles;
        this.prevLocations  = prevLocations;
    }

    /** A live ESG field: its generating ship and the generator. */
    private static final class Field {
        final Ship ship;
        final ESG  esg;
        Field(Ship ship, ESG esg) { this.ship = ship; this.esg = esg; }
    }

    /** Process every active ESG field for this impulse. Returns log lines. */
    List<String> processFields() {
        List<String> log = new ArrayList<>();
        int impulse = game.getAbsoluteImpulse();

        // Pass 1: release announced fields, expire old ones, and gather the live fields.
        List<Field> active = new ArrayList<>();
        for (Ship ship : ships) {
            if (ship.getLocation() == null) {
                continue;
            }
            for (Weapon w : ship.getWeapons().fetchAllWeapons()) {
                if (!(w instanceof ESG)) {
                    continue;
                }
                ESG esg = (ESG) w;
                // Release a previously-announced field (G23.31). It forms now but does
                // NOT damage anything this impulse — only units that ENTER on a later
                // impulse are hit (G23.56/.46).
                if (esg.readyToRelease(impulse)) {
                    esg.release(impulse);
                    if (esg.isActive()) {
                        log.add("  " + ship.getName() + "'s ESG field formed at radius "
                                + esg.getRadius() + " — strength " + esg.getStrength() + " (G23.44)");
                    } else {
                        log.add("  " + ship.getName() + "'s ESG released with no stored energy — no field (G23.3121)");
                    }
                    continue;
                }
                if (!esg.isActive()) {
                    continue;
                }
                if (esg.isExpired(impulse)) {
                    esg.deactivate();
                    esg.recordDrop(impulse);
                    log.add("  " + ship.getName() + "'s ESG field collapsed — 32 impulses elapsed (G23.32)");
                    continue;
                }
                active.add(new Field(ship, esg));
            }
        }

        // Pass 2: ESG-vs-ESG (G23.73) — fields from different ships whose rings share a
        // hex damage each other. This is priority 2 in G23.52, ahead of units (step 5).
        resolveFieldVsField(active, impulse, log);

        // Pass 3: each surviving field damages the units that entered it (G23.51/.52).
        for (Field f : active) {
            if (f.esg.isActive()) {
                processField(f.ship, f.esg, log);
            }
        }
        return log;
    }

    /**
     * Resolve ESG-vs-ESG interactions (G23.73): two fields generated by different ships
     * whose rings occupy a common hex strike each other, each reducing the other by its
     * strength (the smaller collapses; equal fields destroy each other). Fields on the
     * same ship do not interact this way (G23.12 — they operate independently).
     */
    private void resolveFieldVsField(List<Field> active, int impulse, List<String> log) {
        for (int i = 0; i < active.size(); i++) {
            Field a = active.get(i);
            if (!a.esg.isActive()) {
                continue;
            }
            for (int j = i + 1; j < active.size(); j++) {
                Field b = active.get(j);
                if (!b.esg.isActive() || a.ship == b.ship) {
                    continue;
                }
                if (!ringsIntersect(a.ship.getLocation(), a.esg.getRadius(),
                                    b.ship.getLocation(), b.esg.getRadius())) {
                    continue;
                }
                int as = a.esg.getStrength();
                int bs = b.esg.getStrength();
                a.esg.absorbDamage(bs); // each field takes the other's strength (G23.73)
                b.esg.absorbDamage(as);
                if (!a.esg.isActive()) { a.esg.recordDrop(impulse); }
                if (!b.esg.isActive()) { b.esg.recordDrop(impulse); }
                log.add("  " + a.ship.getName() + "'s and " + b.ship.getName()
                        + "'s ESG fields struck each other (" + as + " vs " + bs + ", G23.73)");
                if (!a.esg.isActive()) {
                    break; // this field is gone — move to the next one
                }
            }
        }
    }

    /**
     * True if the radius-{@code rA} ring around {@code cA} and the radius-{@code rB} ring
     * around {@code cB} share at least one hex (G23.73). Scans A's ring and tests each
     * hex against B's range.
     */
    static boolean ringsIntersect(Location cA, int rA, Location cB, int rB) {
        if (cA == null || cB == null) {
            return false;
        }
        for (int x = cA.getX() - rA; x <= cA.getX() + rA; x++) {
            for (int y = cA.getY() - rA; y <= cA.getY() + rA; y++) {
                Location h = new Location(x, y);
                if (MapUtils.getRange(cA, h) == rA && MapUtils.getRange(cB, h) == rB) {
                    return true;
                }
            }
        }
        return false;
    }

    private void processField(Ship ship, ESG esg, List<String> log) {
        int r = esg.getRadius();
        Location shipNow  = ship.getLocation();
        Location shipPrev = prevLocations.getOrDefault(ship, shipNow);

        // Candidate targets: ships, drones and seeker-shuttles, and admin/WW
        // shuttles. Plasma is immune (G23.81); the generating ship is not hit by
        // its own field.
        List<Unit> targets = new ArrayList<>(ships);
        for (Seeker s : seekers) {
            if (s instanceof Unit && !(s instanceof PlasmaTorpedo)) {
                targets.add((Unit) s);
            }
        }
        targets.addAll(activeShuttles);

        // Everything that ENTERED the ring this impulse (G23.51/.571) — landed on a
        // ring hex or crossed it as the unit and/or the field-carrying ship moved.
        List<Entrant> entrants = new ArrayList<>();
        for (Unit unit : targets) {
            if (unit == ship || unit.getLocation() == null || unit instanceof PlasmaTorpedo) {
                continue;
            }
            int rPrev = MapUtils.getRange(shipPrev, prevLocations.getOrDefault(unit, unit.getLocation()));
            int rNow  = MapUtils.getRange(shipNow, unit.getLocation());
            if (entersRing(rPrev, rNow, r)) {
                entrants.add(new Entrant(unit));
            }
        }
        if (entrants.isEmpty()) {
            return;
        }

        // G23.52: with several simultaneous entrants the field scores one point on each
        // in turn, smallest size-class first, capped at what destroys each, repeating
        // until the field is spent or all are destroyed. (Priority steps 1–4 — pass-
        // throughs, other ESGs, terrain, mines — aren't reachable in this single-impulse
        // hex model / are later slices; this is step 5, "other units".)
        int dealt = distributeDamage(ship, esg, entrants, log);
        esg.absorbDamage(dealt);
        if (!esg.isActive()) {
            esg.recordDrop(game.getAbsoluteImpulse()); // strength spent → reactivation lockout (G23.323)
        }
    }

    /** One entrant sharing a field's strength this impulse (G23.52). */
    private static final class Entrant {
        final Unit unit;
        final int  cap;   // damage that destroys it (MAX_VALUE for ships, G23.511)
        int        dmg;   // points accumulated so far
        Entrant(Unit unit) {
            this.unit = unit;
            this.cap  = capToDestroy(unit);
        }
    }

    /** Damage needed to destroy a unit; a ship is effectively immune to destruction (G23.511). */
    private static int capToDestroy(Unit unit) {
        if (unit instanceof Drone)   return Math.max(1, ((Drone) unit).getHull());
        if (unit instanceof Shuttle) return Math.max(1, ((Shuttle) unit).getCurrentHull());
        return Integer.MAX_VALUE;
    }

    /**
     * Sort key for the smallest-first share order (G23.52): drones, then shuttles/
     * fighters, then ships (larger size class = smaller hull = earlier). Ties within a
     * band keep list order — the rulebook's die-roll tie-break (G23.52) is not modelled.
     */
    private static long sizeKey(Unit unit) {
        if (unit instanceof Drone)   return 0;
        if (unit instanceof Shuttle) return 1_000;
        if (unit instanceof Ship)    return 2_000 - ((Ship) unit).getSizeClass();
        return 3_000;
    }

    /**
     * Round-robin the field's strength across the entrants (G23.52): one point to each
     * still-alive unit per pass, smallest first, until the field is spent or everyone is
     * at their destroy cap. Returns the total points dealt (to deplete the field once).
     */
    private int distributeDamage(Ship esgShip, ESG esg, List<Entrant> entrants, List<String> log) {
        entrants.sort(java.util.Comparator.comparingLong(e -> sizeKey(e.unit)));
        int[] caps = new int[entrants.size()];
        for (int i = 0; i < caps.length; i++) {
            caps[i] = entrants.get(i).cap;
        }
        int[] dmg = roundRobin(esg.getStrength(), caps);
        int dealt = 0;
        for (int i = 0; i < dmg.length; i++) {
            Entrant e = entrants.get(i);
            e.dmg = dmg[i];
            dealt += dmg[i];
            if (dmg[i] > 0) {
                applyEntrantDamage(esgShip, e, log);
            }
        }
        return dealt;
    }

    /**
     * G23.52 share order: one point per pass to each not-yet-destroyed unit, in the
     * given (smallest-first) order, each capped at {@code caps[i]}, repeating until the
     * field's {@code strength} is spent or every unit is destroyed. Returns the points
     * dealt to each unit (parallel to {@code caps}).
     */
    static int[] roundRobin(int strength, int[] caps) {
        int[] dmg = new int[caps.length];
        boolean[] destroyed = new boolean[caps.length];
        int remaining = strength;
        int live = caps.length;
        while (remaining > 0 && live > 0) {
            for (int i = 0; i < caps.length && remaining > 0; i++) {
                if (destroyed[i]) {
                    continue;
                }
                dmg[i]++;
                remaining--;
                if (dmg[i] >= caps[i]) {
                    destroyed[i] = true;
                    live--;
                }
            }
        }
        return dmg;
    }

    /**
     * True if a unit whose range to the ESG ship was {@code rPrev} at the start of
     * the impulse and {@code rNow} at the end has ENTERED the radius-{@code r} ring
     * this impulse — either landing on it or crossing it (G23.51/.571). A unit
     * already on the ring at the start of the impulse is not re-entering. Because
     * ships move one hex at a time, a single mover changes the range by at most one;
     * only combined same-impulse movement can jump the ring, and that still counts
     * as entering (the target cannot "jump" the field unharmed, G23.571).
     */
    static boolean entersRing(int rPrev, int rNow, int r) {
        if (rPrev == r) {
            return false; // already in the field at the start of the impulse
        }
        return Math.min(rPrev, rNow) <= r && r <= Math.max(rPrev, rNow);
    }

    /** Apply one entrant's accumulated ESG damage (G23.51): ship→facing shield, seeker/shuttle→destroy or wound. */
    private void applyEntrantDamage(Ship esgShip, Entrant e, List<String> log) {
        Unit unit = e.unit;
        boolean destroyed = e.dmg >= e.cap;

        if (unit instanceof Ship) {
            // The field scores on the shield facing the generating ship (G23.513).
            Ship target = (Ship) unit;
            int shieldNum = game.getShieldNumber(esgShip, target);
            game.markShieldDamage(target, shieldNum, e.dmg);
            log.add("  " + esgShip.getName() + "'s ESG field struck " + target.getName()
                    + " (shield #" + shieldNum + ", " + e.dmg + " points, G23.51)");

        } else if (unit instanceof Drone) {
            Drone drone = (Drone) unit;
            if (destroyed) {
                seekers.remove(drone);
                if (drone.getController() instanceof DroneController) {
                    ((DroneController) drone.getController()).releaseControl(drone);
                }
                log.add("  " + esgShip.getName() + "'s ESG field destroyed a drone (G23.51)");
            } else {
                log.add("  " + esgShip.getName() + "'s ESG field hit a drone for " + e.dmg);
            }

        } else if (unit instanceof Shuttle) {
            Shuttle shuttle = (Shuttle) unit;
            if (destroyed) {
                game.removeShuttleFromPlay(shuttle, "destroyed by ESG field");
                log.add("  " + esgShip.getName() + "'s ESG field destroyed " + shuttle.getName() + " (G23.51)");
            } else {
                shuttle.setCurrentHull(shuttle.getCurrentHull() - e.dmg);
                log.add("  " + esgShip.getName() + "'s ESG field hit " + shuttle.getName() + " for " + e.dmg);
            }
        }
    }
}
