package com.sfb;

import java.util.ArrayList;
import java.util.List;

import com.sfb.objects.Unit;
import com.sfb.objects.shuttles.Fighter;
import com.sfb.objects.shuttles.Shuttle;
import com.sfb.properties.EwLoan;
import com.sfb.utilities.MapUtils;

/**
 * Lending electronic warfare to a squadron (J4.92, J4.93).
 * <p>
 * J4.92 explains why this is a squadron rule and not a scout rule: "While a fighter could
 * receive lent EW from a scout under (G24.217), there will be far too many fighters in
 * place for the scout to support each one as an individual. Instead, fighters are grouped
 * into squadrons (J4.46) and the squadron is lent EW as a whole."
 * <p>
 * The lending is not divided up. J4.93: "Each of the fighters receives all of the loaned
 * points from the loaning unit" — one EW fighter's four points of ECM reach every
 * qualifying squadron-mate at full strength, which is what makes an EWF worth its entire
 * drone armament.
 *
 * <h2>What may be lent</h2>
 * J4.965 is the load-bearing restriction: "Only those points generated by the EWPs, and
 * not the built-in points, can be lent to the other fighters in the squadron." So J4.47's
 * universal two-and-two stays home, and an EWF with no pods lends nothing at all. The same
 * clause says the pod points are "used by the EWF in addition to its built-in EW" — so
 * unlike a carrier (J4.931, which generates a separate set), an EWF's pod points do double
 * duty: it uses them AND lends them. That also makes J4.932's bar on re-lending borrowed
 * points structurally impossible here, since only pod points are ever offered.
 *
 * <h2>What is NOT built here</h2>
 * <ul>
 *   <li>J4.93/J4.931/J4.942 carrier lending — ten hexes, capped by sensor rating, from a
 *       pool the carrier generates separately from its own EW. It needs that second pool on
 *       the ship, which does not exist yet. {@link #loanTo} is the one place that would
 *       learn about it.</li>
 *   <li>J4.943/J4.944 MRS and SWAC lending, neither craft being built.</li>
 *   <li>J4.95 dogfights — a fighter in one cannot use lent points, though the lender keeps
 *       lending them so they take effect the moment the dogfight ends. There is no
 *       dogfight system (J7.0) to ask.</li>
 * </ul>
 */
class SquadronEwResolver {

    /** J4.921: three hexes from an EWF, MRS or SWAC of one's own squadron. */
    static final int SQUADMATE_LEND_RANGE = 3;

    private final Game game;
    private final List<Shuttle> activeShuttles;

    SquadronEwResolver(Game game, List<Shuttle> activeShuttles) {
        this.game = game;
        this.activeShuttles = activeShuttles;
    }

    /**
     * Whether {@code source} could lend to {@code recipient} at this instant (J4.921).
     * <p>
     * Every clause here is about the moment, not about the arrangement: J4.922 keeps a
     * fighter tied to a source that has drifted out of range or been crippled, and this
     * method is what then reports that the points cannot be used.
     */
    boolean qualifiesNow(Fighter recipient, Unit source) {
        return refusalReason(recipient, source) == null;
    }

    /**
     * Why {@code source} is not lending to {@code recipient} right now, or null if it is.
     * <p>
     * The reason and the verdict are the same method because a player looking at a fighter
     * that is getting nothing needs to know WHICH clause bit — J4.921 has four, and "no lent
     * EW" with no explanation is the least useful thing a readout can say. It is also the
     * only way the two cannot drift: {@link #qualifiesNow} is one line over this.
     */
    String refusalReason(Fighter recipient, Unit source) {
        if (recipient == null || source == null || recipient == source)
            return "no source";
        // J4.923: "A crippled shuttle can receive lent EW (J1.333)." The recipient's own
        // condition is deliberately not tested — only the LENDER must be uncrippled.
        if (!(source instanceof Fighter ewf))
            return source.getName() + " cannot lend to a squadron";  // see the class note
        if (!ewf.isTwoSeater())
            return ewf.getName() + " is not an EW fighter (R1.F7)";
        if (ewf.isCrippled())
            return ewf.getName() + " is crippled (J4.921)";
        // J1.343: "A shuttle cannot loan EW points ... for 1/4 turn (eight impulses) after its
        // most recent launch" — the same wait its own phasers serve under J1.342. Only the
        // LENDER waits: the rule's last sentence is "A shuttle can receive EW lending
        // immediately upon launch", which is also what J4.922 means when it cites J1.343. So
        // the recipient's own launch impulse is deliberately not consulted anywhere here.
        int wait = ewf.impulsesUntilEwLending(game.getAbsoluteImpulse());
        if (wait > 0)
            return ewf.getName() + " launched too recently — " + wait + " more impulse"
                    + (wait == 1 ? "" : "s") + " before it may lend (J1.343)";
        if (!recipient.sharesSquadronWith(ewf))
            return ewf.getName() + " is not in " + recipient.getName()
                    + "'s squadron (J4.921)";
        // J4.921: the RECIPIENT holds the lock-on, which is the reverse of a scout channel
        // (G24.218, where the scout must hold it).
        if (!recipient.hasLockOn(ewf))
            return recipient.getName() + " has no lock-on to " + ewf.getName() + " (J4.921)";
        if (recipient.getLocation() == null || ewf.getLocation() == null)
            return ewf.getName() + " is not on the map";
        int range = MapUtils.getRange(recipient, ewf);
        if (range > SQUADMATE_LEND_RANGE)
            return ewf.getName() + " is " + range + " hexes away; J4.921 allows "
                    + SQUADMATE_LEND_RANGE;
        return null;
    }

    /**
     * This fighter's squadron EW fighter, whether or not it can currently lend.
     * <p>
     * Distinct from {@link #effectiveSource}, which answers only when the points are actually
     * flowing. A formation that has strung out needs to know how far away its EW fighter is in
     * order to close up again, and a source that has stopped qualifying is exactly when that
     * matters most.
     */
    Fighter squadronEwFighter(Fighter member) {
        if (member == null || member.getSquadron() == null)
            return null;
        for (Fighter mate : member.getSquadron().getFighters())
            if (mate != member && mate.isTwoSeater() && mate.getEwPods() > 0)
                return mate;
        return null;
    }

    /** Every unit {@code recipient} could designate right now (J4.921). */
    List<Unit> lendingCandidates(Fighter recipient) {
        List<Unit> candidates = new ArrayList<>();
        if (recipient == null)
            return candidates;
        for (Shuttle shuttle : activeShuttles)
            if (shuttle instanceof Fighter other && qualifiesNow(recipient, other))
                candidates.add(other);
        return candidates;
    }

    /**
     * Point {@code recipient} at a lending source, or pass null to stop receiving.
     * <p>
     * J4.922 governs the choice: "A given fighter can only receive 'lent' EW points from a
     * single outside source. It can change the source it is receiving from every eight
     * impulses." Taking a first source is not a change — J1.343 lets a fighter "begin
     * receiving points immediately after launch" — so only swapping one source for another
     * waits out the eight.
     *
     * @return why not, or null if the designation was made
     */
    String designateSource(Fighter recipient, Unit source) {
        if (recipient == null)
            return "no fighter given";
        int now = game.getAbsoluteImpulse();
        Unit current = recipient.getLentEwSource();
        if (current != null && current != source) {
            int since = now - recipient.getLentEwSourceImpulse();
            if (since < Fighter.LENT_EW_SOURCE_INTERVAL)
                return recipient.getName() + " has been receiving EW from "
                        + current.getName() + " for only " + since
                        + " impulses; a fighter may change source every "
                        + Fighter.LENT_EW_SOURCE_INTERVAL + " (J4.922)";
        }
        if (source != null && !qualifiesNow(recipient, source))
            return source.getName() + " cannot lend EW to " + recipient.getName()
                    + " — J4.921 wants an uncrippled EW fighter of the same squadron"
                    + " within " + SQUADMATE_LEND_RANGE + " hexes, with a lock-on to it";
        recipient.setLentEwSource(source, now);
        return null;
    }

    /**
     * The unit actually lending to {@code recipient}: whatever it was explicitly pointed at,
     * or failing that its own squadron's EW fighter.
     * <p>
     * The implicit half is what J4.93 describes. The designation there belongs to the LENDER,
     * not the recipient: "A given carrier, EWF, MRS, or SWAC can loan the points it is
     * generating to all fighters (of a designated squadron) that are within the appropriate
     * distance and otherwise qualify." An EWF lends to its squadron; the squadron does not
     * apply to it one fighter at a time. So a squadron-mate needs no instruction to benefit.
     * <p>
     * J4.922's single-source rule is not bypassed by this, because with one EWF per squadron
     * (J4.463) and carrier lending unbuilt there is at present only ever one source to have.
     * The clock that rule sets exists to stop a player hopping between sources impulse by
     * impulse to chase the best EW, and it has nothing to bite on until a fighter can be in
     * two lenders' reach. When carrier lending arrives, an explicit designation is how the
     * player picks — and it wins here, which is why it is consulted first.
     */
    Unit effectiveSource(Fighter recipient) {
        if (recipient == null)
            return null;
        Unit declared = recipient.getLentEwSource();
        if (declared != null)
            return declared;
        return squadronLender(recipient);
    }

    /**
     * The EW fighter of {@code recipient}'s own squadron that can lend to it right now.
     * <p>
     * J4.463 allows a squadron only one, so the search is really a lookup; it is written as a
     * search because a squadron whose EWF is crippled or out of range should simply find
     * nothing rather than find it and be told no.
     */
    private Unit squadronLender(Fighter recipient) {
        com.sfb.objects.Squadron squadron = recipient.getSquadron();
        if (squadron == null)
            return null;
        for (Fighter mate : squadron.getFighters())
            if (mate != recipient && qualifiesNow(recipient, mate))
                return mate;
        return null;
    }

    /**
     * The points {@code recipient} is actually getting from its source.
     * <p>
     * Empty where the source has become unusable, which for a DECLARED source is not the
     * same as having no source: J4.922 says a fighter "cannot change just because the present
     * source became unavailable but would have to continue 'receiving' from that unit (even
     * though it could not use the points)". The designation survives; the points stop. An
     * implicit squadron source has no such stickiness — nothing was declared, so there is
     * nothing to be held to.
     */
    EwLoan loanTo(Fighter recipient) {
        if (recipient == null)
            return EwLoan.NONE;
        Unit source = effectiveSource(recipient);
        if (!qualifiesNow(recipient, source))
            return EwLoan.NONE;
        Fighter ewf = (Fighter) source;
        // J4.965: the pods only. getPodEcm/getPodEccm already return nothing when the pods
        // are switched off (J4.967) or shot away with the fighter (J1.3322), and the split
        // between them is the one declared under J4.961.
        //
        // G24.2174: "a fighter cannot receive more than four points of ECM or four points
        // of ECCM." J4.941's eight combined is the same ceiling seen from the lender's end
        // — four pods make eight points — so capping each half here satisfies both.
        return new EwLoan(Math.min(Fighter.MAX_LENT_RECEIVED, ewf.getPodEcm()),
                Math.min(Fighter.MAX_LENT_RECEIVED, ewf.getPodEccm()));
    }

    /**
     * Drop any designation pointing at a unit that has left the map, so a recovered or
     * destroyed EWF does not hold its squadron to a source that no longer exists.
     * <p>
     * J4.922's stickiness is about a source that is still out there and merely unusable. A
     * fighter back in its hangar is not a source at all.
     */
    void releaseSource(Unit departed) {
        for (Shuttle shuttle : activeShuttles)
            if (shuttle instanceof Fighter f && f.getLentEwSource() == departed)
                f.setLentEwSource(null, game.getAbsoluteImpulse());
    }
}
