package com.sfb;

import static org.junit.Assert.*;

import java.util.LinkedHashMap;
import java.util.Map;

import org.junit.Before;
import org.junit.Test;

import com.sfb.objects.Ship;
import com.sfb.objects.Squadron;
import com.sfb.objects.shuttles.Haas;
import com.sfb.objects.shuttles.Haas_E;
import com.sfb.properties.Location;
import com.sfb.systemgroups.Energy;
import com.sfb.systemgroups.EwCircuits;

/**
 * A carrier lending EW to its squadrons (J4.93, J4.931, J4.933).
 * <p>
 * The other half of J4.921, and a different animal from the EW fighter's. An EWF lends the
 * points its pods make, using them itself at the same time (J4.965). A carrier generates a
 * SECOND set for the purpose — J4.931: "generated in a special manner (under an equal limit)
 * separately from those points generated by the carrier for its own use. The same points cannot
 * be used by both the carrier and the fighters."
 * <p>
 * Ten hexes rather than three, and only to its own squadrons; only a fully capable carrier may
 * do it at all.
 */
public class CarrierEwLendingTest {

    private Game game;
    private Ship carrier;
    private Ship enemy;
    private Squadron squadron;
    private Haas wingman;

    @Before
    public void setUp() {
        game = new Game();
        Player kzinti = new Player();
        kzinti.setTeamName("Kzinti");
        Player fed = new Player();
        fed.setTeamName("Federation");

        carrier = new Ship();
        carrier.init(com.sfb.samples.KzintiShips.getKzinBC());
        carrier.setName("KHS Longsword");
        carrier.setLocation(new Location(10, 10));
        carrier.setFacing(1);
        carrier.setOwner(kzinti);
        carrier.setCarrierClass(com.sfb.properties.CarrierClass.CAPABLE);
        game.getShips().add(carrier);

        enemy = new Ship();
        enemy.init(com.sfb.samples.FederationShips.getFedCa());
        enemy.setName("USS Attacker");
        enemy.setLocation(new Location(10, 25));
        enemy.setFacing(13);
        enemy.setActiveFireControl(true);
        game.getShips().add(enemy);

        wingman = new Haas();
        wingman.setName("HAAS-1");
        wingman.setOwner(kzinti);
        wingman.setLocation(new Location(10, 14));   // four hexes out: past an EWF, inside a carrier
        wingman.setFacing(13);
        game.getActiveShuttles().add(wingman);

        squadron = new Squadron("Gold", carrier);
        assertNull(squadron.add(wingman));
        carrier.getShuttles().getSquadrons().add(squadron);

        game.startTurn();
        wingman.addLockOn(carrier);                  // J4.921 wants one on the lender
    }

    /**
     * Declare a squadron pool the way a turn does: allocateEnergy STORES the form, and
     * Ship.startTurn() is what applies it — which is where J4.931's pool is filled, the same
     * place the scout's lending pool (G24.211) is.
     */
    private void generate(String squadronName, int ecm, int eccm) {
        Map<String, int[]> declared = new LinkedHashMap<>();
        declared.put(squadronName, new int[] { ecm, eccm });
        applyAllocation(declared);
    }

    private void applyAllocation(Map<String, int[]> declared) {
        Energy e = new Energy();
        e.setLifeSupport(carrier.getLifeSupportCost());
        if (declared != null)
            e.setSquadronEw(declared);
        carrier.allocateEnergy(e);
        carrier.startTurn();
    }

    // -------------------------------------------------------------------------
    // The loan
    // -------------------------------------------------------------------------

    @Test
    public void aCarrierLendsWhatItGeneratedForTheSquadron() {
        generate("Gold", 4, 2);

        assertSame(carrier, game.lentEwSourceOf(wingman));
        assertEquals(4, game.lentEwTo(wingman).ecm());
        assertEquals(2, game.lentEwTo(wingman).eccm());
        assertEquals("2 built-in (J4.47) + 4 lent, held to J4.91's six",
                6, game.ewAgainst(enemy, wingman).total());
    }

    /** J4.921: ten hexes, not the EW fighter's three. */
    @Test
    public void tenHexesIsTheLimit() {
        generate("Gold", 4, 2);
        wingman.setLocation(new Location(10, 20));   // exactly ten
        assertFalse(game.lentEwTo(wingman).isNothing());

        wingman.setLocation(new Location(10, 21));   // eleven
        assertTrue(game.lentEwTo(wingman).isNothing());
        String why = game.ewLendRefusalFor(wingman);
        assertTrue("should name the range and the rule: " + why,
                why.contains("11 hexes") && why.contains("J4.921"));
    }

    /** J4.931/J4.6: a casual carrier may not use the procedure at all. */
    @Test
    public void aCasualCarrierMayNotLend() {
        carrier.setCarrierClass(com.sfb.properties.CarrierClass.CASUAL);
        generate("Gold", 4, 2);

        assertTrue("nothing generated for it either", game.lentEwTo(wingman).isNothing());
        assertFalse("the pool should have been zeroed", squadron.hasCarrierEw());
    }

    /** J4.921: its "specific home carrier", not a friendly one that happens to be close. */
    @Test
    public void aStrangersCarrierLendsNothing() {
        generate("Gold", 4, 2);

        Ship otherCarrier = new Ship();
        otherCarrier.init(com.sfb.samples.KzintiShips.getKzinBC());
        otherCarrier.setName("KHS Elsewhere");
        otherCarrier.setLocation(new Location(11, 14));   // right next to the fighter
        otherCarrier.setFacing(1);
        otherCarrier.setOwner(carrier.getOwner());
        otherCarrier.setCarrierClass(com.sfb.properties.CarrierClass.CAPABLE);
        game.getShips().add(otherCarrier);
        wingman.addLockOn(otherCarrier);

        assertNotNull(game.designateLentEwSource(wingman, otherCarrier));
        assertSame("still its own carrier", carrier, game.lentEwSourceOf(wingman));
    }

    /** J4.931: the pool is generated at allocation, so a turn without a declaration lends none. */
    @Test
    public void anUndeclaredTurnLendsNothing() {
        assertFalse(squadron.hasCarrierEw());
        assertTrue(game.lentEwTo(wingman).isNothing());
        String why = game.ewLendRefusalFor(wingman);
        assertTrue("should say so: " + why, why.contains("generated no EW"));
    }

    /** And the pool does not carry over: a fresh allocation with nothing in it clears it. */
    @Test
    public void thePoolIsFreshEachTurn() {
        generate("Gold", 4, 2);
        assertTrue(squadron.hasCarrierEw());

        applyAllocation(null);                // a turn with nothing declared

        assertFalse(squadron.hasCarrierEw());
        assertTrue(game.lentEwTo(wingman).isNothing());
    }

    // -------------------------------------------------------------------------
    // The limits
    // -------------------------------------------------------------------------

    /**
     * J4.931's "equal limit" — the carrier's own generation limit, which is
     * min(sensor rating, 6). J4.942's separate sensor-rating cap is always the looser of the
     * two, so this is the one that bites.
     */
    @Test
    public void thePoolIsCappedByTheGenerationLimit() {
        int limit = EwCircuits.generationLimit(carrier.getSpecialFunctions().getSensor());
        generate("Gold", limit + 3, 0);

        assertEquals("trimmed to the limit", limit,
                squadron.getCarrierEcm() + squadron.getCarrierEccm());
        assertTrue("and the player is told: " + carrier.getAllocationNotes(),
                carrier.getAllocationNotes().stream().anyMatch(n -> n.contains("J4.931")));
    }

    /** The cap is on the TOTAL, not on each half (the J4.93 example's "to a total of six"). */
    @Test
    public void theCapIsOnTheTotal() {
        int limit = EwCircuits.generationLimit(carrier.getSpecialFunctions().getSensor());
        generate("Gold", limit - 1, 1);

        assertEquals(limit - 1, squadron.getCarrierEcm());
        assertEquals(1, squadron.getCarrierEccm());
    }

    /**
     * J4.933: "generate a separate set of EW points for each group (assuming it has the power;
     * yes this means it could generate twelve EW)." The pools are independent, not a split.
     */
    @Test
    public void eachSquadronGetsItsOwnPool() {
        Squadron second = new Squadron("Blue", carrier);
        Haas other = new Haas();
        other.setName("HAAS-2");
        other.setOwner(carrier.getOwner());
        other.setLocation(new Location(10, 13));
        game.getActiveShuttles().add(other);
        assertNull(second.add(other));
        carrier.getShuttles().getSquadrons().add(second);
        other.addLockOn(carrier);

        Map<String, int[]> declared = new LinkedHashMap<>();
        declared.put("Gold", new int[] { 4, 2 });
        declared.put("Blue", new int[] { 2, 4 });
        applyAllocation(declared);

        assertEquals("Gold's own six", 4, game.lentEwTo(wingman).ecm());
        assertEquals("and Blue's own six, not a share of one pool",
                2, game.lentEwTo(other).ecm());
        assertEquals(4, game.lentEwTo(other).eccm());
    }

    /** G24.2174 still caps what a FIGHTER may receive, however much the carrier generated. */
    @Test
    public void aFighterStillReceivesNoMoreThanFour() {
        generate("Gold", 6, 0);

        assertEquals("six generated, four received (G24.2174)",
                4, game.lentEwTo(wingman).ecm());
    }

    // -------------------------------------------------------------------------
    // Two sources at once (J4.922)
    // -------------------------------------------------------------------------

    /**
     * The J4.93 example's situation: an EW fighter within three hexes and the carrier within
     * ten, both offering. J4.922 allows only one, and the default takes the better offer —
     * "any fighter receiving the points couldn't benefit from the points from the EWF since a
     * fighter can only receive lent points from a single source".
     */
    @Test
    public void withTwoOffersTheBetterOneIsTaken() {
        Haas_E ewf = new Haas_E();
        ewf.setName("HAAS-E");
        ewf.setOwner(carrier.getOwner());
        ewf.setLocation(new Location(10, 15));       // one hex from the wingman
        game.getActiveShuttles().add(ewf);
        assertNull(squadron.add(ewf));
        wingman.addLockOn(ewf);

        // The EWF's two pods make four points; the carrier generates six.
        generate("Gold", 4, 2);

        assertSame("the carrier's six beats the EWF's four", carrier,
                game.lentEwSourceOf(wingman));
        assertEquals(4, game.lentEwTo(wingman).ecm());

        // Take the carrier's pool away and the EWF is the better offer again.
        applyAllocation(null);
        assertSame(ewf, game.lentEwSourceOf(wingman));
        assertEquals(2, game.lentEwTo(wingman).ecm());
    }

    /** A declared source still wins over the default, and J4.922 holds it for eight impulses. */
    @Test
    public void anExplicitDesignationOverridesTheBetterOffer() {
        Haas_E ewf = new Haas_E();
        ewf.setName("HAAS-E");
        ewf.setOwner(carrier.getOwner());
        ewf.setLocation(new Location(10, 15));
        game.getActiveShuttles().add(ewf);
        assertNull(squadron.add(ewf));
        wingman.addLockOn(ewf);
        generate("Gold", 4, 2);

        assertNull(game.designateLentEwSource(wingman, ewf));
        assertSame("the player's choice, not the arithmetic's", ewf,
                game.lentEwSourceOf(wingman));
        assertEquals(2, game.lentEwTo(wingman).ecm());

        String no = game.designateLentEwSource(wingman, carrier);
        assertNotNull("and J4.922 holds it there", no);
        assertTrue(no.contains("J4.922"));
    }
}
