package com.sfb;

import com.sfb.objects.Ship;
import com.sfb.properties.Location;
import com.sfb.samples.FederationShips;
import com.sfb.systemgroups.Energy;
import com.sfb.weapons.ESG;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * ESG-vs-ESG interaction (G23.73): two fields generated by different ships whose
 * rings share a hex strike each other, each reducing the other by its strength —
 * the smaller collapses, equal fields destroy each other.
 */
public class EsgVsEsgTest {

    // --- ringsIntersect geometry ---

    @Test
    public void ringsThatTouch_intersect() {
        // r2 ring at (10,10) and r1 ring at (10,13): range 3 = rA+rB, tangent at (10,12).
        assertTrue(EsgResolver.ringsIntersect(new Location(10, 10), 2, new Location(10, 13), 1));
    }

    @Test
    public void ringsFarApart_doNotIntersect() {
        assertFalse(EsgResolver.ringsIntersect(new Location(10, 10), 2, new Location(10, 20), 1));
    }

    @Test
    public void containedRing_doesNotIntersect_g2371OverlapDeferred() {
        // A small ring wholly inside a larger field's disc: the rings never touch, so
        // G23.73 does not fire. Catching this static overlap is G23.71/.712 (deferred).
        assertFalse(EsgResolver.ringsIntersect(new Location(10, 10), 3, new Location(10, 11), 1));
    }

    // --- field-vs-field strike through the impulse engine ---

    private Ship esgShip(Game game, String name, int x, int y, int radius, int energy) {
        Ship ship = new Ship();
        ship.init(FederationShips.getFedCa());
        ship.setName(name);
        ship.setLocation(new Location(x, y));
        ship.setFacing(1);
        ESG esg = new ESG();
        esg.setDesignator("A");
        ship.getWeapons().addWeapon(esg);
        esg.setStoredEnergy(energy);
        esg.activate(radius, 0);
        game.getShips().add(ship);
        return ship;
    }

    private ESG esgOf(Ship ship) {
        for (com.sfb.weapons.Weapon w : ship.getWeapons().fetchAllWeapons()) {
            if (w instanceof ESG) return (ESG) w;
        }
        return null;
    }

    private Energy alloc(Ship ship) {
        Energy e = new Energy();
        e.setLifeSupport(ship.getLifeSupportCost());
        e.setFireControl(ship.getFireControlCost());
        e.setActivateShields(ship.getActiveShieldCost());
        e.setWarpMovement(0.0); // both stationary; the rings already overlap
        return e;
    }

    /** Advance phases until a field-vs-field strike has resolved (or give up). */
    private void runImpulse(Game game, ESG watch) {
        for (int guard = 0; guard < 80; guard++) {
            game.advancePhase();
            if (!watch.isActive()) return;
        }
    }

    @Test
    public void unequalFields_smallerCollapses_largerReducedByItsStrength() {
        Game game = new Game();
        Ship a = esgShip(game, "Azure",  10, 10, 2, 2); // chart[2][2] = 7
        Ship b = esgShip(game, "Bronze", 10, 13, 1, 1); // chart[1][1] = 4
        game.startTurn();
        game.submitAllocation(a, alloc(a));
        game.submitAllocation(b, alloc(b));

        assertEquals(7, esgOf(a).getStrength());
        assertEquals(4, esgOf(b).getStrength());

        runImpulse(game, esgOf(b));

        assertFalse("the weaker field (4) collapses", esgOf(b).isActive());
        assertTrue("the stronger field survives", esgOf(a).isActive());
        assertEquals("reduced by the other's strength (7 - 4)", 3, esgOf(a).getStrength());
    }

    @Test
    public void equalFields_destroyEachOther() {
        Game game = new Game();
        Ship a = esgShip(game, "Azure",  10, 10, 2, 2); // chart[2][2] = 7
        Ship b = esgShip(game, "Bronze", 10, 13, 1, 2); // chart[1][2] = 7
        game.startTurn();
        game.submitAllocation(a, alloc(a));
        game.submitAllocation(b, alloc(b));

        assertEquals(7, esgOf(a).getStrength());
        assertEquals(7, esgOf(b).getStrength());

        runImpulse(game, esgOf(a));

        assertFalse("equal fields destroy each other (G23.73)", esgOf(a).isActive());
        assertFalse(esgOf(b).isActive());
    }
}
